version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      postgresql:
        patterns:
          - "*postgresql*"
      maven:
        patterns:
          - "*maven*"
      kotlin:
        patterns:
          - "*kotlin*"
