### Create a product
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Block of buttons",
  "description": "Buttons driven by the J",
  "category": "Super Smartphones",
  "price": 100
}

### Search for products
GET http://localhost:8080/products/search?q=100
Accept: application/json

### Reset all
POST http://localhost:8080/products/reset
