services:
  api-service:
    ports:
      - "8080:8080"
  postgres:
    ports:
      - "5432:5432"

  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    ports:
      - "5601:5601"