package org.jesperancinha.supermarket.delivery.domain

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.Table
import java.time.Instant
import java.util.UUID

// The id is generated by Hibernate at insert time (GenerationType.UUID), not assigned by the
// application. Assigning a non-null id client-side made Spring Data's default "is this a new
// entity" check (id == null) always false, so save() issued a merge (extra SELECT) instead of
// an insert for brand-new rows.
@Entity
@Table(name = "deliveries")
data class Delivery(
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(columnDefinition = "UUID", updatable = false, nullable = false)
    val id: UUID? = null,
    val vehicleId: String,
    val address: String,
    val startedAt: Instant,
    val finishedAt: Instant?,
    @Enumerated(EnumType.STRING)
    val status: DeliveryStatus
)
