version: '3'

services:
  postgres:
    hostname: postgres
    build:
      context: docker-psql/.
    env_file: docker-psql/.env
    user: postgres
    volumes:
      - ./docker-psql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
