name: Library Books - PR

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'adopt'

        - name: Build
          run:  make build-maven

        - name: Test
          run:  make test-maven
