name: RNS Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 19
          uses: actions/setup-java@v4
          with:
            java-version: '19'
            distribution: 'adopt'

        - name: Make full build
          run: make b

        - name: Build and Test
          run: make build-report
